# Indian Brand Name → Generic Name Mapper
# Add more drugs here as needed

INDIAN_DRUG_MAP = {

    # ─── Pain / Fever / Anti-inflammatory ───────────────────────────────
    "dolo 650": "paracetamol",
    "dolo": "paracetamol",
    "crocin": "paracetamol",
    "crocin advance": "paracetamol",
    "calpol": "paracetamol",
    "paracip": "paracetamol",
    "p 500": "paracetamol",
    "febrinil": "paracetamol",
    "metacin": "paracetamol",
    "combiflam": "ibuprofen paracetamol",
    "brufen": "ibuprofen",
    "ibugesic": "ibuprofen",
    "ibugesic plus": "ibuprofen paracetamol",
    "advil": "ibuprofen",
    "nurofen": "ibuprofen",
    "voveran": "diclofenac",
    "voltaren": "diclofenac",
    "voltaflam": "diclofenac",
    "reactin": "diclofenac",
    "moov": "diclofenac",
    "dynapar": "diclofenac",
    "diclomol": "diclofenac paracetamol",
    "ultracet": "tramadol paracetamol",
    "tramazac": "tramadol",
    "contramal": "tramadol",
    "naprosyn": "naproxen",
    "flanax": "naproxen",
    "meftal": "mefenamic acid",
    "meftal spas": "mefenamic acid dicyclomine",
    "nise": "nimesulide",
    "nimulid": "nimesulide",
    "etoshine": "etoricoxib",
    "nucoxia": "etoricoxib",
    "arcoxia": "etoricoxib",
    "celebrex": "celecoxib",
    "cox 2": "celecoxib",
    "ketorol": "ketorolac",
    "ketanov": "ketorolac",
    "toradol": "ketorolac",
    "pirox": "piroxicam",
    "dolonex": "piroxicam",

    # ─── Antibiotics ─────────────────────────────────────────────────────
    "augmentin": "amoxicillin clavulanate",
    "augmentin 625": "amoxicillin clavulanate",
    "mox": "amoxicillin",
    "novamox": "amoxicillin",
    "amoxil": "amoxicillin",
    "azithral": "azithromycin",
    "zithromax": "azithromycin",
    "azee": "azithromycin",
    "azicip": "azithromycin",
    "althrocin": "erythromycin",
    "ciplox": "ciprofloxacin",
    "cifran": "ciprofloxacin",
    "ciprobid": "ciprofloxacin",
    "taxim": "cefotaxime",
    "taxim o": "cefixime",
    "monocef": "ceftriaxone",
    "ceftum": "cefuroxime",
    "cefpodoxime": "cefpodoxime",
    "zifi": "cefixime",
    "cefolac": "cefixime",
    "metrogyl": "metronidazole",
    "flagyl": "metronidazole",
    "metron": "metronidazole",
    "tiniba": "tinidazole",
    "fasigyn": "tinidazole",
    "doxrid": "doxycycline",
    "doxt sl": "doxycycline",
    "vibramycin": "doxycycline",
    "levoflox": "levofloxacin",
    "tavanic": "levofloxacin",
    "loxof": "levofloxacin",
    "oflox": "ofloxacin",
    "zanocin": "ofloxacin",
    "clavam": "amoxicillin clavulanate",
    "meronem": "meropenem",
    "merrem": "meropenem",
    "clindamycin": "clindamycin",
    "dalacin": "clindamycin",
    "vancomycin": "vancomycin",
    "linezolid": "linezolid",
    "lizolid": "linezolid",
    "nitrofurantoin": "nitrofurantoin",
    "macrobid": "nitrofurantoin",
    "bactrim": "trimethoprim sulfamethoxazole",
    "septran": "trimethoprim sulfamethoxazole",

    # ─── Antifungals ─────────────────────────────────────────────────────
    "zocon": "fluconazole",
    "forcan": "fluconazole",
    "diflucan": "fluconazole",
    "vfend": "voriconazole",
    "canesten": "clotrimazole",
    "clotrimazole": "clotrimazole",
    "terbicip": "terbinafine",
    "lamisil": "terbinafine",
    "itraconazole": "itraconazole",
    "canditral": "itraconazole",
    "sporanox": "itraconazole",
    "griseofulvin": "griseofulvin",

    # ─── Antivirals ──────────────────────────────────────────────────────
    "acivir": "acyclovir",
    "zovirax": "acyclovir",
    "valaclovir": "valacyclovir",
    "valcivir": "valacyclovir",
    "tamiflu": "oseltamivir",
    "antiflu": "oseltamivir",
    "molnupiravir": "molnupiravir",
    "molulife": "molnupiravir",

    # ─── Antacids / GI / Liver ───────────────────────────────────────────
    "pan 40": "pantoprazole",
    "pan 20": "pantoprazole",
    "pan": "pantoprazole",
    "pantocid": "pantoprazole",
    "pantop": "pantoprazole",
    "omez": "omeprazole",
    "omez d": "omeprazole domperidone",
    "prilosec": "omeprazole",
    "razo": "rabeprazole",
    "rablet": "rabeprazole",
    "pariet": "rabeprazole",
    "nexpro": "esomeprazole",
    "nexium": "esomeprazole",
    "esomac": "esomeprazole",
    "gelusil": "aluminum hydroxide magnesium hydroxide",
    "digene": "aluminum hydroxide magnesium hydroxide",
    "mucaine": "aluminum hydroxide magnesium hydroxide oxethazaine",
    "gasex": "herbal antacid",
    "rantac": "ranitidine",
    "zinetac": "ranitidine",
    "aciloc": "ranitidine",
    "famocid": "famotidine",
    "pepcid": "famotidine",
    "emeset": "ondansetron",
    "ondansetron": "ondansetron",
    "zofran": "ondansetron",
    "vomilast": "ondansetron",
    "perinorm": "metoclopramide",
    "reglan": "metoclopramide",
    "domstal": "domperidone",
    "motilium": "domperidone",
    "domperi": "domperidone",
    "imodium": "loperamide",
    "eldoper": "loperamide",
    "buscopan": "hyoscine butylbromide",
    "cyclopam": "dicyclomine",
    "colospa": "mebeverine",
    "librax": "chlordiazepoxide clidinium",
    "udiliv": "ursodeoxycholic acid",
    "ursocol": "ursodeoxycholic acid",
    "heptral": "ademetionine",
    "silymarin": "silymarin",
    "livolin": "silymarin",
    "normaxin": "chlordiazepoxide clidinium",
    "cremaffin": "liquid paraffin milk of magnesia",
    "duphalac": "lactulose",
    "looz": "lactulose",

    # ─── Heart / Blood Pressure ───────────────────────────────────────────
    "stamlo": "amlodipine",
    "amlokind": "amlodipine",
    "amlong": "amlodipine",
    "norvasc": "amlodipine",
    "telma": "telmisartan",
    "telmikind": "telmisartan",
    "telma h": "telmisartan hydrochlorothiazide",
    "telsar": "telmisartan",
    "losartan": "losartan",
    "losar": "losartan",
    "cosart": "losartan",
    "olsar": "olmesartan",
    "benicar": "olmesartan",
    "arkamin": "clonidine",
    "catapres": "clonidine",
    "aten": "atenolol",
    "tenormin": "atenolol",
    "metolar": "metoprolol",
    "metolar xr": "metoprolol",
    "betaloc": "metoprolol",
    "lopressor": "metoprolol",
    "concor": "bisoprolol",
    "corbis": "bisoprolol",
    "carvedilol": "carvedilol",
    "cardivas": "carvedilol",
    "nebicard": "nebivolol",
    "nebilet": "nebivolol",
    "cardace": "ramipril",
    "altace": "ramipril",
    "lisinopril": "lisinopril",
    "listril": "lisinopril",
    "zestril": "lisinopril",
    "enalapril": "enalapril",
    "envas": "enalapril",
    "vasotec": "enalapril",
    "amlodac": "amlodipine",
    "amlopin": "amlodipine",
    "ecosprin": "aspirin",
    "loprin": "aspirin",
    "aspirin": "aspirin",
    "disprin": "aspirin",
    "clopivas": "clopidogrel",
    "deplatt": "clopidogrel",
    "plavix": "clopidogrel",
    "prasugrel": "prasugrel",
    "effient": "prasugrel",
    "ticagrelor": "ticagrelor",
    "brilinta": "ticagrelor",
    "warfarin": "warfarin",
    "warf": "warfarin",
    "coumadin": "warfarin",
    "acitrom": "acenocoumarol",
    "dabigatran": "dabigatran",
    "pradaxa": "dabigatran",
    "xarelto": "rivaroxaban",
    "rivaroxaban": "rivaroxaban",
    "apixaban": "apixaban",
    "eliquis": "apixaban",
    "digoxin": "digoxin",
    "lanoxin": "digoxin",
    "lasix": "furosemide",
    "frumil": "furosemide",
    "frusemide": "furosemide",
    "dytor": "torsemide",
    "torasemide": "torsemide",
    "aldactone": "spironolactone",
    "spironolactone": "spironolactone",
    "nitroglycerin": "nitroglycerin",
    "nitrostat": "nitroglycerin",
    "isordil": "isosorbide dinitrate",
    "imdur": "isosorbide mononitrate",
    "monotrate": "isosorbide mononitrate",
    "amiodarone": "amiodarone",
    "cordarone": "amiodarone",
    "ivabradine": "ivabradine",
    "coralan": "ivabradine",
    "ranolazine": "ranolazine",
    "ranexa": "ranolazine",
    "hydralazine": "hydralazine",
    "minipress": "prazosin",
    "prazosin": "prazosin",
    "doxazosin": "doxazosin",
    "cardura": "doxazosin",

    # ─── Diabetes ─────────────────────────────────────────────────────────
    "glycomet": "metformin",
    "glycomet gp": "metformin glimepiride",
    "glucophage": "metformin",
    "obimet": "metformin",
    "amaryl": "glimepiride",
    "glimestar": "glimepiride",
    "glimpid": "glimepiride",
    "glimy": "glimepiride",
    "glipizide": "glipizide",
    "glucotrol": "glipizide",
    "glyburide": "glyburide",
    "daonil": "glibenclamide",
    "glibenclamide": "glibenclamide",
    "januvia": "sitagliptin",
    "istavel": "sitagliptin",
    "galvus": "vildagliptin",
    "zomelis": "vildagliptin",
    "trajenta": "linagliptin",
    "linagliptin": "linagliptin",
    "onglyza": "saxagliptin",
    "saxagliptin": "saxagliptin",
    "jardiance": "empagliflozin",
    "empagliflozin": "empagliflozin",
    "farxiga": "dapagliflozin",
    "dapagliflozin": "dapagliflozin",
    "forxiga": "dapagliflozin",
    "invokana": "canagliflozin",
    "canagliflozin": "canagliflozin",
    "byetta": "exenatide",
    "victoza": "liraglutide",
    "ozempic": "semaglutide",
    "rybelsus": "semaglutide",
    "insulin": "insulin",
    "huminsulin": "insulin",
    "lantus": "insulin glargine",
    "basalog": "insulin glargine",
    "novorapid": "insulin aspart",
    "actrapid": "insulin regular",
    "pioglitazone": "pioglitazone",
    "piosys": "pioglitazone",
    "actos": "pioglitazone",
    "acarbose": "acarbose",
    "glucobay": "acarbose",

    # ─── Cholesterol / Lipids ─────────────────────────────────────────────
    "storvas": "atorvastatin",
    "atorlip": "atorvastatin",
    "lipitor": "atorvastatin",
    "rozavel": "rosuvastatin",
    "crestor": "rosuvastatin",
    "rosuvas": "rosuvastatin",
    "simvastatin": "simvastatin",
    "zocor": "simvastatin",
    "pravastatin": "pravastatin",
    "pravachol": "pravastatin",
    "lovastatin": "lovastatin",
    "pitavastatin": "pitavastatin",
    "fenofibrate": "fenofibrate",
    "tricor": "fenofibrate",
    "lopid": "gemfibrozil",
    "gemfibrozil": "gemfibrozil",
    "ezetimibe": "ezetimibe",
    "ezetrol": "ezetimibe",
    "vytorin": "ezetimibe simvastatin",
    "niacin": "niacin",
    "evolocumab": "evolocumab",
    "repatha": "evolocumab",

    # ─── Thyroid ──────────────────────────────────────────────────────────
    "eltroxin": "levothyroxine",
    "thyronorm": "levothyroxine",
    "thyrox": "levothyroxine",
    "synthroid": "levothyroxine",
    "carbimazole": "carbimazole",
    "neomercazole": "carbimazole",
    "propylthiouracil": "propylthiouracil",
    "thyrozol": "thiamazole",

    # ─── Allergy / Cold / Respiratory ────────────────────────────────────
    "cetrizine": "cetirizine",
    "alerid": "cetirizine",
    "zyrtec": "cetirizine",
    "cetzine": "cetirizine",
    "montair": "montelukast",
    "singulair": "montelukast",
    "montair lc": "montelukast levocetirizine",
    "allegra": "fexofenadine",
    "fexofenadine": "fexofenadine",
    "levocet": "levocetirizine",
    "xyzal": "levocetirizine",
    "lcz": "levocetirizine",
    "atarax": "hydroxyzine",
    "hydroxyzine": "hydroxyzine",
    "benadryl": "diphenhydramine",
    "diphenhydramine": "diphenhydramine",
    "pheniramine": "pheniramine",
    "avil": "pheniramine",
    "chlorpheniramine": "chlorpheniramine",
    "piriton": "chlorpheniramine",
    "deriphyllin": "theophylline etofylline",
    "theophylline": "theophylline",
    "theo 24": "theophylline",
    "salbutamol": "salbutamol",
    "asthalin": "salbutamol",
    "ventolin": "salbutamol",
    "levolin": "levosalbutamol",
    "levosalbutamol": "levosalbutamol",
    "formoterol": "formoterol",
    "foracort": "budesonide formoterol",
    "seretide": "salmeterol fluticasone",
    "symbicort": "budesonide formoterol",
    "tiotropium": "tiotropium",
    "spiriva": "tiotropium",
    "budesonide": "budesonide",
    "pulmicort": "budesonide",
    "fluticasone": "fluticasone",
    "flixotide": "fluticasone",
    "beclate": "beclomethasone",
    "ipratropium": "ipratropium",
    "atrovent": "ipratropium",
    "mucolite": "ambroxol",
    "ambrodil": "ambroxol",
    "ambroxol": "ambroxol",
    "alex": "chlorpheniramine dextromethorphan",
    "benadryl cough": "diphenhydramine",
    "dextromethorphan": "dextromethorphan",
    "guaifenesin": "guaifenesin",
    "grilinctus": "dextromethorphan guaifenesin",

    # ─── Sleep / Anxiety / Psychiatric ───────────────────────────────────
    "alprax": "alprazolam",
    "restyl": "alprazolam",
    "xanax": "alprazolam",
    "lonazep": "clonazepam",
    "rivotril": "clonazepam",
    "clonazepam": "clonazepam",
    "diazepam": "diazepam",
    "valium": "diazepam",
    "calmpose": "diazepam",
    "lorazepam": "lorazepam",
    "ativan": "lorazepam",
    "larpose": "lorazepam",
    "nexito": "escitalopram",
    "stalopam": "escitalopram",
    "lexapro": "escitalopram",
    "fluoxetine": "fluoxetine",
    "fludac": "fluoxetine",
    "prozac": "fluoxetine",
    "sertraline": "sertraline",
    "serta": "sertraline",
    "zoloft": "sertraline",
    "zosert": "sertraline",
    "paroxetine": "paroxetine",
    "pexep": "paroxetine",
    "paxil": "paroxetine",
    "venlafaxine": "venlafaxine",
    "venlor": "venlafaxine",
    "effexor": "venlafaxine",
    "duloxetine": "duloxetine",
    "duzela": "duloxetine",
    "cymbalta": "duloxetine",
    "mirtazapine": "mirtazapine",
    "mirtaz": "mirtazapine",
    "remeron": "mirtazapine",
    "amitriptyline": "amitriptyline",
    "tryptomer": "amitriptyline",
    "elavil": "amitriptyline",
    "imipramine": "imipramine",
    "tofranil": "imipramine",
    "lithium": "lithium",
    "priadel": "lithium",
    "quetiapine": "quetiapine",
    "seroquel": "quetiapine",
    "qutan": "quetiapine",
    "olanzapine": "olanzapine",
    "oliza": "olanzapine",
    "zyprexa": "olanzapine",
    "risperidone": "risperidone",
    "risperdal": "risperidone",
    "sizodon": "risperidone",
    "haloperidol": "haloperidol",
    "serenace": "haloperidol",
    "haldol": "haloperidol",
    "clozapine": "clozapine",
    "sizopin": "clozapine",
    "clozaril": "clozapine",
    "aripiprazole": "aripiprazole",
    "arip mt": "aripiprazole",
    "abilify": "aripiprazole",
    "zolpidem": "zolpidem",
    "nitrest": "zolpidem",
    "ambien": "zolpidem",
    "melatonin": "melatonin",

    # ─── Epilepsy / Neurology ─────────────────────────────────────────────
    "phenytoin": "phenytoin",
    "eptoin": "phenytoin",
    "dilantin": "phenytoin",
    "carbamazepine": "carbamazepine",
    "tegretol": "carbamazepine",
    "mazetol": "carbamazepine",
    "valproate": "valproic acid",
    "encorate": "valproic acid",
    "depakote": "valproic acid",
    "valparin": "valproic acid",
    "levetiracetam": "levetiracetam",
    "levroxa": "levetiracetam",
    "keppra": "levetiracetam",
    "gabapentin": "gabapentin",
    "gabantin": "gabapentin",
    "neurontin": "gabapentin",
    "pregabalin": "pregabalin",
    "lyrica": "pregabalin",
    "pregeb": "pregabalin",
    "topiramate": "topiramate",
    "topamac": "topiramate",
    "lamotrigine": "lamotrigine",
    "lamitor": "lamotrigine",
    "lamictal": "lamotrigine",
    "oxcarbazepine": "oxcarbazepine",
    "oxcarb": "oxcarbazepine",
    "donepezil": "donepezil",
    "aricept": "donepezil",
    "memantine": "memantine",
    "namenda": "memantine",
    "rivastigmine": "rivastigmine",
    "exelon": "rivastigmine",
    "levodopa carbidopa": "levodopa carbidopa",
    "syndopa": "levodopa carbidopa",
    "sinemet": "levodopa carbidopa",
    "pramipexole": "pramipexole",
    "mirapex": "pramipexole",
    "ropinirole": "ropinirole",
    "requip": "ropinirole",
    "rasagiline": "rasagiline",
    "rasalect": "rasagiline",
    "azilect": "rasagiline",
    "sumatriptan": "sumatriptan",
    "suminat": "sumatriptan",
    "imitrex": "sumatriptan",
    "rizatriptan": "rizatriptan",
    "rizact": "rizatriptan",

    # ─── Steroids / Immunosuppressants ───────────────────────────────────
    "wysolone": "prednisolone",
    "omnacortil": "prednisolone",
    "prednisolone": "prednisolone",
    "betnesol": "betamethasone",
    "betamethasone": "betamethasone",
    "dexona": "dexamethasone",
    "dexamethasone": "dexamethasone",
    "medrol": "methylprednisolone",
    "solu medrol": "methylprednisolone",
    "methylprednisolone": "methylprednisolone",
    "hydrocortisone": "hydrocortisone",
    "efcortesol": "hydrocortisone",
    "azathioprine": "azathioprine",
    "imuran": "azathioprine",
    "cyclosporine": "cyclosporine",
    "panimun bioral": "cyclosporine",
    "tacrolimus": "tacrolimus",
    "prograf": "tacrolimus",
    "mycophenolate": "mycophenolate",
    "cellcept": "mycophenolate",
    "methotrexate": "methotrexate",
    "folitrax": "methotrexate",

    # ─── Cancer / Oncology (common oral) ─────────────────────────────────
    "imatinib": "imatinib",
    "gleevec": "imatinib",
    "veenat": "imatinib",
    "gefitinib": "gefitinib",
    "iressa": "gefitinib",
    "erlotinib": "erlotinib",
    "tarceva": "erlotinib",
    "letrozole": "letrozole",
    "femara": "letrozole",
    "anastrozole": "anastrozole",
    "arimidex": "anastrozole",
    "tamoxifen": "tamoxifen",
    "nolvadex": "tamoxifen",
    "exemestane": "exemestane",
    "aromasin": "exemestane",
    "capecitabine": "capecitabine",
    "xeloda": "capecitabine",
    "sorafenib": "sorafenib",
    "nexavar": "sorafenib",
    "lenalidomide": "lenalidomide",
    "revlimid": "lenalidomide",

    # ─── Vitamins / Supplements ───────────────────────────────────────────
    "becosules": "vitamin b complex",
    "becosules z": "vitamin b complex zinc",
    "limcee": "vitamin c",
    "celin": "vitamin c",
    "calcirol": "vitamin d3",
    "arachitol": "vitamin d3",
    "shelcal": "calcium carbonate vitamin d3",
    "shelcal hd": "calcium carbonate vitamin d3",
    "zincovit": "zinc multivitamin",
    "zevit": "zinc vitamin b complex",
    "rejunuron": "methylcobalamin",
    "mecobalamin": "methylcobalamin",
    "nurokind": "methylcobalamin",
    "b12": "cyanocobalamin",
    "folic acid": "folic acid",
    "folvite": "folic acid",
    "ferrous sulfate": "ferrous sulfate",
    "livogen": "ferrous fumarate folic acid",
    "ferium xt": "ferrous ascorbate folic acid",
    "orofer s": "ferric hydroxide sucrose",
    "iron sucrose": "iron sucrose",
    "zinc": "zinc",
    "zinconia": "zinc",
    "omega 3": "omega 3 fatty acids",
    "maxirich": "multivitamin",
    "supradyn": "multivitamin",
    "revital": "multivitamin",
    "cod liver oil": "cod liver oil",

    # ─── Antiparasitic / Antihelmintic ───────────────────────────────────
    "albendazole": "albendazole",
    "zentel": "albendazole",
    "noworm": "albendazole",
    "mebendazole": "mebendazole",
    "vermox": "mebendazole",
    "ivermectin": "ivermectin",
    "ivermectin tablet": "ivermectin",
    "stromectol": "ivermectin",
    "chloroquine": "chloroquine",
    "lariago": "chloroquine",
    "hydroxychloroquine": "hydroxychloroquine",
    "hcqs": "hydroxychloroquine",
    "plaquenil": "hydroxychloroquine",
    "primaquine": "primaquine",
    "artemether lumefantrine": "artemether lumefantrine",
    "coartem": "artemether lumefantrine",

    # ─── Urology / Kidney ─────────────────────────────────────────────────
    "tamsulosin": "tamsulosin",
    "urimax": "tamsulosin",
    "flomax": "tamsulosin",
    "silodosin": "silodosin",
    "urimax d": "tamsulosin dutasteride",
    "finasteride": "finasteride",
    "finpecia": "finasteride",
    "proscar": "finasteride",
    "dutasteride": "dutasteride",
    "avodart": "dutasteride",
    "oxybutynin": "oxybutynin",
    "ditropan": "oxybutynin",
    "solifenacin": "solifenacin",
    "vesicare": "solifenacin",
    "tolterodine": "tolterodine",
    "detrol": "tolterodine",
    "desmopressin": "desmopressin",
    "minirin": "desmopressin",

    # ─── Skin / Dermatology (oral/topical oral) ───────────────────────────
    "isotretinoin": "isotretinoin",
    "sotret": "isotretinoin",
    "accutane": "isotretinoin",
    "tretinoin": "tretinoin",
    "retin a": "tretinoin",
    "acitretin": "acitretin",
    "soriatane": "acitretin",
    "dapsone": "dapsone",
    "dapson": "dapsone",

    # ─── Eye Drops (common) ───────────────────────────────────────────────
    "timolol": "timolol",
    "timoptol": "timolol",
    "latanoprost": "latanoprost",
    "xalatan": "latanoprost",
    "bimatoprost": "bimatoprost",
    "bimat": "bimatoprost",
    "lumigan": "bimatoprost",
    "dorzolamide": "dorzolamide",
    "trusopt": "dorzolamide",
    "brimonidine": "brimonidine",
    "alphagan": "brimonidine",
    "moxifloxacin eye": "moxifloxacin",
    "vigamox": "moxifloxacin",
    "tobramycin": "tobramycin",
    "tobrex": "tobramycin",

    # ─── Miscellaneous / Others ───────────────────────────────────────────
    "hydroxyzine hcl": "hydroxyzine",
    "colchicine": "colchicine",
    "zyloric": "allopurinol",
    "allopurinol": "allopurinol",
    "febuxostat": "febuxostat",
    "febustat": "febuxostat",
    "uloric": "febuxostat",
    "sildenafil": "sildenafil",
    "viagra": "sildenafil",
    "penegra": "sildenafil",
    "tadalafil": "tadalafil",
    "cialis": "tadalafil",
    "tadalis": "tadalafil",
    "vardenafil": "vardenafil",
    "levitra": "vardenafil",
    "cabergoline": "cabergoline",
    "dostinex": "cabergoline",
    "bromocriptine": "bromocriptine",
    "cyclogest": "progesterone",
    "duphaston": "dydrogesterone",
    "dydrogesterone": "dydrogesterone",
    "primolut n": "norethisterone",
    "norethisterone": "norethisterone",
    "mtp kit": "mifepristone misoprostol",
    "misoprostol": "misoprostol",
    "mifepristone": "mifepristone",
    "oxytocin": "oxytocin",
    "pitocin": "oxytocin",
    "methylergonovine": "methylergonovine",
    "methergine": "methylergonovine",
    "heparin": "heparin",
    "clexane": "enoxaparin",
    "enoxaparin": "enoxaparin",
    "atropine": "atropine",
    "adrenaline": "epinephrine",
    "epinephrine": "epinephrine",
    "dopamine": "dopamine",
    "dobutamine": "dobutamine",
    "noradrenaline": "norepinephrine",
    "naloxone": "naloxone",
    "narcan": "naloxone",
    "naltrexone": "naltrexone",
    "antabuse": "disulfiram",
    "disulfiram": "disulfiram",
    "baclofen": "baclofen",
    "lioresal": "baclofen",
    "tizanidine": "tizanidine",
    "tizan": "tizanidine",
    "carisoprodol": "carisoprodol",
    "soma": "carisoprodol",
    "sucralfate": "sucralfate",
    "sucrafil": "sucralfate",
    "carafate": "sucralfate",
    "mesalamine": "mesalamine",
    "mesacol": "mesalamine",
    "pentasa": "mesalamine",
    "sulfasalazine": "sulfasalazine",
    "salazopyrin": "sulfasalazine",
    "infliximab": "infliximab",
    "remicade": "infliximab",
    "adalimumab": "adalimumab",
    "humira": "adalimumab",
}


def get_generic_name(brand_name: str) -> str | None:
    """
    Convert Indian brand name to generic name.
    Returns None if brand not found in mapper.
    For combination drugs (e.g. 'ibuprofen paracetamol'), returns the full string.
    Use get_generic_names_list() to split combos into individual ingredients.
    """
    key = brand_name.strip().lower()
    return INDIAN_DRUG_MAP.get(key, None)


def get_generic_names_list(brand_name: str) -> list[str]:
    """
    Like get_generic_name, but splits combination generics into a list.
    e.g. 'combiflam' -> ['ibuprofen', 'paracetamol']
    Returns [] if brand not found.
    """
    generic = get_generic_name(brand_name)
    if not generic:
        return []
    return generic.split()